### ISSUE TITLE
wyze-bridge

### ISSUE THREAD

**Issue by nicholaswilde** [nicholaswilde/home-assistant#1]
https://github.com/CCOSTAN/Docker_Support/blob/4ab5e92ff40650124f298a6ce35964ef1b0a5e92/docker-compose.yaml
```
wyze-bridge:
      image: mrlt8/wyze-bridge:latest
      container_name: wyze-bridge
      restart: unless-stopped
      ports:
          - 5000:5000 # Web UI
          - 1935:1935 # RTMP
          - 8554:8554 # RTSP
          - 8888:8888 # HLS
      environment:
          - WYZE_EMAIL=Carlo@vcloudinfo # Replace with wyze email
          - WYZE_PASSWORD=PasswordPasswordPassword # Replace with wyze password
          - IGNORE_OFFLINE=true 
          - QUALITY=SD30
          - SNAPSHOT=RTSP
```
