### ISSUE TITLE
Zigbee2MQTT

### ISSUE THREAD

**Issue by nicholaswilde** [nicholaswilde/home-assistant#13]
https://www.zigbee2mqtt.io/guide/installation/02_docker.html

**Comment by nicholaswilde** [comment]
```
version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0
```
