### ISSUE TITLE
Lomi Notification

### ISSUE THREAD

**Issue by nicholaswilde** [nicholaswilde/home-assistant#29]
https://community.home-assistant.io/t/detect-when-appliance-is-finished-based-on-power-usage/325672/15

```yaml
alias: dishwasher done notification
description: ''
trigger:
  - platform: numeric_state
    entity_id: sensor.a_d_power
    above: '700'
    below: '1100'
    for: '00:10:00'
condition:
  - condition: numeric_state
    entity_id: sensor.b_c_power
    below: '700'
action:
  - wait_for_trigger:
      - platform: numeric_state
        entity_id: sensor.a_d_power
        below: '400'
        for: '00:05:00'
    continue_on_timeout: false
    timeout: '00:30:00'
  - wait_for_trigger:
      - platform: numeric_state
        entity_id: sensor.a_d_power
        below: '1100'
        for: '00:10:00'
        above: '700'
    continue_on_timeout: false
    timeout: '01:00:00'
  - wait_for_trigger:
      - platform: numeric_state
        entity_id: sensor.a_d_power
        below: '400'
        for: '00:30:00'
    continue_on_timeout: false
    timeout: '01:00:00'
  - service: notify.mobile_app_pixel_5
    data:
      message: dishwasher done
mode: parallel
max: 3
```
