### ISSUE TITLE
rtl_433

### ISSUE THREAD

**Issue by nicholaswilde** [nicholaswilde/home-assistant#59]
https://github.com/hertzg/rtl_433_docker
```yaml
version: "3"
services:
  rtl433:
    image: hertzg/rtl_433:latest
    devices:
      - "/dev/bus/usb/001/003"
    command:
      - "-Mtime:unix:usec:utc"
      - "-Mbits"
      - "-Mlevel"
      - "-Mprotocol"
      - "-Mstats:2:300"
      - "-Fmqtt://mosquitto:1883,retain=1"
      - "-Finflux://influxdb:8086/write?db=rtl433"

  mosquitto: ...

  influxdb: ...
```
